permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 冯廉义
  email: 1324928301@qq.com
  link: http://fly1324928301.github.io
  weibo: http://blog.sina.com.cn/flyliam
  github: http://github.com/Fly1324928301

# 站点信息
title: 冯廉义的博客 
description: 冯廉义的博客
url: http://fly1324928301.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/icon/xiaobai.png
favicon: /public/icon/xiaobai.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - iOS

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
